on:
  push:
    branches: testing

name: Update rgee
jobs:
  update-rgee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6
